// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Agent from "@dfinity/agent";

function createActor(idlFactory, canisterId) {
  var agent = new Agent.HttpAgent();
  return Agent.Actor.createActor(idlFactory, {
              agent: agent,
              canisterId: canisterId
            });
}

export {
  createActor ,
  
}
/* @dfinity/agent Not a pure module */
