// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.js";
import * as AuthClient from "@dfinity/auth-client";

function toString(e) {
  switch (e.TAG | 0) {
    case /* LoginError */0 :
        return "Authorization login error:" + e._0;
    case /* PromiseError */1 :
        return "Authorization promise error";
    case /* Timeout */2 :
        return "Authorization timeout:" + e._0.toString() + " seconds";
    
  }
}

var $$Error = {
  toString: toString
};

function authenticate(onSuccess, onError, timeoutInSeconds) {
  var timeoutId = setTimeout((function (param) {
          return Curry._1(onError, {
                      TAG: /* Timeout */2,
                      _0: timeoutInSeconds
                    });
        }), timeoutInSeconds * 1000);
  return $$Promise.$$catch(AuthClient.AuthClient.create().then(function (authClient) {
                  return authClient.login({
                              onSuccess: (function () {
                                  clearTimeout(timeoutId);
                                  return Curry._1(onSuccess, authClient.getIdentity().getPrincipal().toString());
                                }),
                              onError: (function (error) {
                                  clearTimeout(timeoutId);
                                  return Curry._1(onError, {
                                              TAG: /* LoginError */0,
                                              _0: error
                                            });
                                })
                            });
                }), (function (exn) {
                clearTimeout(timeoutId);
                Curry._1(onError, {
                      TAG: /* PromiseError */1,
                      _0: exn
                    });
                return Promise.resolve(undefined);
              }));
}

export {
  $$Error ,
  authenticate ,
  
}
/* @dfinity/auth-client Not a pure module */
