// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Backend from "dfx-generated/backend";

var Actor = {};

var Candid = {
  Actor: Actor
};

var actor = Backend.backend;

export {
  Candid ,
  actor ,
  
}
/* actor Not a pure module */
