// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Agent from "./Agent.js";
import * as Backend from "dfx-generated/backend";

var actor = Agent.createActor(Backend.idlFactory, Backend.canisterId);

export {
  actor ,
  
}
/* actor Not a pure module */
