// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Config from "./Config.js";
import * as $$Object from "./Object.js";
import * as Random from "rescript/lib/es6/random.js";
import * as Sprite from "./Sprite.js";

function memPos(objs, x, y) {
  return objs.some(function (param) {
              var px = param.px;
              var py = param.py;
              if (x === px) {
                return y === py;
              } else {
                return false;
              }
            });
}

function trimEdge(x, y, level) {
  var pixx = Config.blockw(level) * 16;
  var pixy = Config.blockh(level) * 16;
  return !(x < 128 || pixx - x < 528 || y === 0 || pixy - y < 48);
}

function convertCoinToObj(param, state) {
  return $$Object.make(false, undefined, undefined, {
              TAG: /* Item */3,
              _0: /* Coin */1
            }, state, Sprite.makeParams(/* Coin */1), param[1], param[2]);
}

function addCoins(state, x, y0) {
  var y = y0 - 16;
  if (Random.bool(undefined) && trimEdge(x, y, state.level) && !memPos(state.objects, x, y)) {
    state.objects.push(convertCoinToObj([
              /* QBlockCoin */1,
              x,
              y
            ], state));
    return ;
  }
  
}

function convertEnemyToObj(param, state) {
  var enemyTyp = param[0];
  var obj = $$Object.make(undefined, undefined, undefined, {
        TAG: /* Enemy */2,
        _0: enemyTyp
      }, state, Sprite.enemyParams(enemyTyp, /* Left */0), param[1], param[2]);
  $$Object.setVelToSpeed(obj);
  return obj;
}

function randomEnemyTyp(param) {
  var match = Random.$$int(3);
  if (match !== 0) {
    if (match !== 1) {
      return /* Goomba */0;
    } else {
      return /* GKoopa */1;
    }
  } else {
    return /* RKoopa */2;
  }
}

function addEnemyOnBlock(state, x, y) {
  var placeEnemy = Random.$$int(Config.enemyDensity(state.level));
  if (placeEnemy === 0 && !memPos(state.objects, x, y - 16)) {
    state.objects.push(convertEnemyToObj([
              randomEnemyTyp(undefined),
              x,
              y - 16
            ], state));
    return ;
  }
  
}

function addBlock(state, blockTyp, xBlock, yBlock) {
  var x = xBlock * 16;
  var y = yBlock * 16;
  if (!(!memPos(state.objects, x, y) && trimEdge(x, y, state.level))) {
    return ;
  }
  var obj = $$Object.make(undefined, undefined, undefined, {
        TAG: /* Block */4,
        _0: blockTyp
      }, state, Sprite.blockParams(blockTyp), x, y);
  state.objects.push(obj);
  addCoins(state, x, y);
  return addEnemyOnBlock(state, x, y);
}

function generateGroundStairs(cbx, cby, typ, state) {
  addBlock(state, typ, cbx, cby);
  addBlock(state, typ, cbx + 1, cby);
  addBlock(state, typ, cbx + 2, cby);
  addBlock(state, typ, cbx + 3, cby);
  addBlock(state, typ, cbx + 1, cby - 1);
  addBlock(state, typ, cbx + 2, cby - 1);
  addBlock(state, typ, cbx + 3, cby - 1);
  addBlock(state, typ, cbx + 2, cby - 2);
  addBlock(state, typ, cbx + 3, cby - 2);
  return addBlock(state, typ, cbx + 3, cby - 3);
}

function generateAirupStairs(cbx, cby, typ, state) {
  addBlock(state, typ, cbx, cby);
  addBlock(state, typ, cbx + 1, cby);
  addBlock(state, typ, cbx + 3, cby - 1);
  addBlock(state, typ, cbx + 4, cby - 1);
  addBlock(state, typ, cbx + 4, cby - 2);
  addBlock(state, typ, cbx + 5, cby - 2);
  return addBlock(state, typ, cbx + 6, cby - 2);
}

function generateAirdownStairs(cbx, cby, typ, state) {
  addBlock(state, typ, cbx, cby);
  addBlock(state, typ, cbx + 1, cby);
  addBlock(state, typ, cbx + 2, cby);
  addBlock(state, typ, cbx + 2, cby + 1);
  addBlock(state, typ, cbx + 3, cby + 1);
  addBlock(state, typ, cbx + 5, cby + 2);
  return addBlock(state, typ, cbx + 6, cby + 2);
}

function generateClouds(_cbx, cby, typ, _num, state) {
  while(true) {
    var num = _num;
    var cbx = _cbx;
    if (num === 0) {
      return ;
    }
    addBlock(state, typ, cbx, cby);
    _num = num - 1 | 0;
    _cbx = cbx + 1;
    continue ;
  };
}

function randomStairTyp(param) {
  if (Random.bool(undefined)) {
    return /* UnBBlock */4;
  } else {
    return /* Brick */3;
  }
}

function chooseBlockPattern(cbx, cby, state) {
  if (cbx > Config.blockw(state.level) || cby > Config.blockh(state.level)) {
    return ;
  }
  var stairTyp = randomStairTyp(undefined);
  var lifeBlock = Random.$$int(5) === 0;
  var middleBlock = lifeBlock ? /* QBlockMushroom */0 : stairTyp;
  var match = Random.$$int(5);
  switch (match) {
    case 0 :
        addBlock(state, stairTyp, cbx, cby);
        addBlock(state, middleBlock, cbx + 1, cby);
        return addBlock(state, stairTyp, cbx + 2, cby);
    case 1 :
        var numClouds = Random.$$int(5) + 5 | 0;
        if (cby < 5) {
          return generateClouds(cbx, cby, /* Cloud */5, numClouds, state);
        } else {
          return ;
        }
    case 2 :
        if (Config.blockh(state.level) - cby === 1) {
          return generateGroundStairs(cbx, cby, stairTyp, state);
        } else {
          return ;
        }
    case 3 :
        if (stairTyp === /* Brick */3 && Config.blockh(state.level) - cby > 3) {
          return generateAirdownStairs(cbx, cby, stairTyp, state);
        } else if (Config.blockh(state.level) - cby > 2) {
          return generateAirupStairs(cbx, cby, stairTyp, state);
        } else {
          return addBlock(state, stairTyp, cbx, cby);
        }
    default:
      if (cby + 3 - Config.blockh(state.level) === 2) {
        return addBlock(state, stairTyp, cbx, cby);
      } else if (cby + 3 - Config.blockh(state.level) === 1) {
        addBlock(state, stairTyp, cbx, cby);
        return addBlock(state, stairTyp, cbx, cby + 1);
      } else {
        addBlock(state, stairTyp, cbx, cby);
        addBlock(state, stairTyp, cbx, cby + 1);
        return addBlock(state, stairTyp, cbx, cby + 2);
      }
  }
}

function generateEnemiesOnGround(_cbx, _cby, state) {
  while(true) {
    var cby = _cby;
    var cbx = _cbx;
    if (cbx > Config.blockw(state.level) - 32) {
      return ;
    }
    if (cby > Config.blockh(state.level) - 1 || cbx < 15) {
      _cby = 0;
      _cbx = cbx + 1;
      continue ;
    }
    if (cby === 0 || Config.blockh(state.level) - 1 !== cby || Random.$$int(10) !== 0) {
      _cby = cby + 1;
      continue ;
    }
    state.objects.push(convertEnemyToObj([
              randomEnemyTyp(undefined),
              cbx * 16,
              cby * 16
            ], state));
    _cby = cby + 1;
    continue ;
  };
}

function generateBlocks(_cbx, _cby, state) {
  while(true) {
    var cby = _cby;
    var cbx = _cbx;
    if (Config.blockw(state.level) - cbx < 33) {
      return ;
    }
    if (cby > Config.blockh(state.level) - 1) {
      _cby = 0;
      _cbx = cbx + 1;
      continue ;
    }
    if (memPos(state.objects, cbx, cby) || cby === 0) {
      _cby = cby + 1;
      continue ;
    }
    if (Random.$$int(20) === 0) {
      chooseBlockPattern(cbx, cby, state);
      _cby = cby + 1;
      continue ;
    }
    _cby = cby + 1;
    continue ;
  };
}

function generatePanel(state) {
  return $$Object.make(undefined, undefined, undefined, {
              TAG: /* Block */4,
              _0: /* Panel */6
            }, state, Sprite.blockParams(/* Panel */6), Config.blockw(state.level) * 16 - 256, Config.blockh(state.level) * 16 * 2 / 3);
}

function convertBlockToObj(param) {
  var y = param[2];
  var x = param[1];
  var blockTyp = param[0];
  var partial_arg = {
    TAG: /* Block */4,
    _0: blockTyp
  };
  var arg = Sprite.blockParams(blockTyp);
  return function (param) {
    return $$Object.make(undefined, undefined, undefined, partial_arg, param, arg, x, y);
  };
}

function generateGround(_inc, state) {
  while(true) {
    var inc = _inc;
    if (inc > Config.blockw(state.level)) {
      return ;
    }
    if (inc > 10) {
      var skip = Random.$$int(10);
      if (skip === 7 && Config.blockw(state.level) - inc > 32) {
        _inc = inc + 1;
        continue ;
      }
      state.objects.push(convertBlockToObj([
                  /* Ground */7,
                  inc * 16,
                  Config.blockh(state.level) * 16
                ])(state));
      _inc = inc + 1;
      continue ;
    }
    state.objects.push(convertBlockToObj([
                /* Ground */7,
                inc * 16,
                Config.blockh(state.level) * 16
              ])(state));
    _inc = inc + 1;
    continue ;
  };
}

function generateHelper(state) {
  generateBlocks(0, 0, state);
  generateGround(0, state);
  generateEnemiesOnGround(0, 0, state);
  var panel = generatePanel(state);
  state.objects.push(panel);
  
}

function newPlayer(playerNum, state) {
  return $$Object.make(undefined, undefined, undefined, playerNum ? ({
                  TAG: /* Player2 */1,
                  _0: /* SmallM */1
                }) : ({
                  TAG: /* Player1 */0,
                  _0: /* SmallM */1
                }), state, Sprite.playerParams(/* SmallM */1, /* Standing */0, /* Left */0, playerNum), 100, 224);
}

function generate(state) {
  Random.init(Config.randomSeed(state.level));
  var initial = performance.now();
  generateHelper(state);
  var elapsed = performance.now() - initial;
  console.log("generated", state.objects.length, "objects in " + (elapsed.toString() + " milliseconds"));
  
}

export {
  memPos ,
  trimEdge ,
  convertCoinToObj ,
  addCoins ,
  convertEnemyToObj ,
  randomEnemyTyp ,
  addEnemyOnBlock ,
  addBlock ,
  generateGroundStairs ,
  generateAirupStairs ,
  generateAirdownStairs ,
  generateClouds ,
  randomStairTyp ,
  chooseBlockPattern ,
  generateEnemiesOnGround ,
  generateBlocks ,
  generatePanel ,
  convertBlockToObj ,
  generateGround ,
  generateHelper ,
  newPlayer ,
  generate ,
  
}
/* Object Not a pure module */
