// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Agent from "./Agent.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Candid from "./Candid.js";
import * as Backend from "dfx-generated/backend";

var actor = Agent.createActor(Backend.idlFactory, Backend.canisterId);

var service = Candid.Service.fromActor(actor);

function printTree(t) {
  if (t.TAG === /* Leaf */0) {
    return String(t._0);
  } else {
    return "(" + printTree(t._0) + ", " + printTree(t._1) + ")";
  }
}

function Main$main(Props) {
  var match = React.useState(function () {
        return "hello";
      });
  var updateState = match[1];
  var state = match[0];
  var onNewTree = function (newTree) {
    var newState = printTree(newTree);
    if (newState !== state) {
      return Curry._1(updateState, (function (param) {
                    return newState;
                  }));
    }
    
  };
  var onTick = function (param) {
    Curry._1(service.get, undefined).then(onNewTree);
    
  };
  React.useEffect((function () {
          var intervalId = setInterval(onTick, 1000);
          return (function (param) {
                    clearInterval(intervalId);
                    
                  });
        }), []);
  var button = function (name, cb) {
    return React.createElement("button", {
                className: "clickMeBtn",
                onClick: (function (param) {
                    Curry._1(cb, undefined);
                    
                  })
              }, name);
  };
  return React.createElement("div", {
              className: "top"
            }, React.createElement("div", {
                  className: "container"
                }, state), React.createElement("section", undefined, button("Extend", service.extend), button("Reverse", service.reverseInPlace), button("Reset", service.reset)));
}

var main = Main$main;

export {
  actor ,
  service ,
  printTree ,
  main ,
  
}
/* actor Not a pure module */
