// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Config from "./Config.js";
import * as Backend from "./Backend.js";
import * as Director from "./Director.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function preload(param) {
  var loadCount = {
    contents: 0
  };
  var numImages = Config.images.length;
  return Belt_Array.forEachU(Config.images, (function (img_src) {
                var img = document.createElement("img");
                img.src = Config.spritesDir + img_src;
                img.addEventListener("load", (function (param) {
                        loadCount.contents = loadCount.contents + 1 | 0;
                        if (loadCount.contents === numImages) {
                          Director.updateLoop(1);
                        }
                        return true;
                      }), true);
                
              }));
}

function start(param) {
  window.onload = (function (param) {
      preload(undefined);
      setInterval(Backend.onTick, 1000);
      return true;
    });
  
}

var Html;

export {
  Html ,
  preload ,
  start ,
  
}
/* Backend Not a pure module */
