// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Director from "./Director.js";

function start(param) {
  window.onload = (function (param) {
      Director.updateLoop(undefined);
      return true;
    });
  
}

export {
  start ,
  
}
/* Director Not a pure module */
