// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sprite from "./Sprite.js";

function make(velOpt, accOpt, partType, px, py) {
  var vel = velOpt !== undefined ? velOpt : ({
        x: 0,
        y: 0
      });
  var acc = accOpt !== undefined ? accOpt : ({
        x: 0,
        y: 0
      });
  var sprite = Sprite.makeParticle(partType);
  var lifetime = partType === 2 || partType === 1 ? 300 : 30;
  return {
          sprite: sprite,
          lifetime: lifetime,
          px: px,
          py: py,
          vel: vel,
          acc: acc,
          kill: false
        };
}

function makeScore(score, pos) {
  var t = score >= 801 ? (
      score >= 2001 ? (
          score !== 4000 ? (
              score !== 8000 ? /* Score100 */3 : /* Score8000 */10
            ) : /* Score4000 */9
        ) : (
          score !== 1000 ? (
              score >= 2000 ? /* Score2000 */8 : /* Score100 */3
            ) : /* Score1000 */7
        )
    ) : (
      score >= 201 ? (
          score !== 400 ? (
              score >= 800 ? /* Score800 */6 : /* Score100 */3
            ) : /* Score400 */5
        ) : (
          score !== 100 && score >= 200 ? /* Score200 */4 : /* Score100 */3
        )
    );
  var partial_arg = {
    x: 0.5,
    y: -0.7
  };
  return function (param) {
    return make(partial_arg, undefined, t, pos, param);
  };
}

function updateVel(part) {
  part.vel.x = part.vel.x + part.acc.x;
  part.vel.y = part.vel.y + part.acc.y;
  
}

function updatePos(part) {
  part.px = part.vel.x + part.px;
  part.py = part.vel.y + part.py;
  
}

function $$process(part) {
  part.lifetime = part.lifetime - 1 | 0;
  if (part.lifetime === 0) {
    part.kill = true;
  }
  updateVel(part);
  return updatePos(part);
}

export {
  make ,
  makeScore ,
  updateVel ,
  updatePos ,
  $$process ,
  
}
/* Sprite Not a pure module */
