// Generated by ReScript, PLEASE EDIT WITH CARE


function create(src) {
  var img = document.createElement("img");
  img.src = src;
  return img;
}

var bgd1 = create("./sprites/bgd-1.png");

var blocks = create("./sprites/blocks.png");

var chunks = create("./sprites/chunks.png");

var enemies = create("./sprites/enemies.png");

var ground = create("./sprites/ground.png");

var items = create("./sprites/items.png");

var marioSmall = create("./sprites/mario-small.png");

var mario2Small = create("./sprites/mario2-small.png");

var marioBig = create("./sprites/mario-big.png");

var mario2Big = create("./sprites/mario2-big.png");

var panel = create("./sprites/panel.png");

var score = create("./sprites/score.png");

function toImg(t) {
  switch (t) {
    case /* Bgd1 */0 :
        return bgd1;
    case /* Blocks */1 :
        return blocks;
    case /* Chunks */2 :
        return chunks;
    case /* Enemies */3 :
        return enemies;
    case /* Ground */4 :
        return ground;
    case /* Items */5 :
        return items;
    case /* MarioSmall */6 :
        return marioSmall;
    case /* Mario2Small */7 :
        return mario2Small;
    case /* MarioBig */8 :
        return marioBig;
    case /* Mario2Big */9 :
        return mario2Big;
    case /* Panel */10 :
        return panel;
    case /* Score */11 :
        return score;
    
  }
}

export {
  create ,
  bgd1 ,
  blocks ,
  chunks ,
  enemies ,
  ground ,
  items ,
  marioSmall ,
  mario2Small ,
  marioBig ,
  mario2Big ,
  panel ,
  score ,
  toImg ,
  
}
/* bgd1 Not a pure module */
