// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

function spriteParams(bboxOffsetOpt, bboxSizeOpt, frameSizeOpt, maxTicksOpt, maxFramesOpt, srcOffset, img) {
  var bboxOffset = bboxOffsetOpt !== undefined ? bboxOffsetOpt : [
      0,
      0
    ];
  var bboxSize = bboxSizeOpt !== undefined ? bboxSizeOpt : [
      0,
      0
    ];
  var frameSize = frameSizeOpt !== undefined ? frameSizeOpt : [
      16,
      16
    ];
  var maxTicks = maxTicksOpt !== undefined ? maxTicksOpt : 0;
  var maxFrames = maxFramesOpt !== undefined ? maxFramesOpt : 1;
  var bboxSize$1 = Caml_obj.caml_equal(bboxSize, [
        0,
        0
      ]) ? frameSize : bboxSize;
  var maxFrames$1 = maxFrames < 1 ? 1 : maxFrames;
  return {
          maxFrames: maxFrames$1,
          maxTicks: maxTicks,
          img: img,
          frameSize: frameSize,
          srcOffset: srcOffset,
          bboxOffset: bboxOffset,
          bboxSize: bboxSize$1
        };
}

function create(src) {
  var img = document.createElement("img");
  img.src = src;
  return img;
}

var marioSmall = create("./sprites/mario-small.png");

var mario2Small = create("./sprites/mario2-small.png");

var marioBig = create("./sprites/mario-big.png");

var mario2Big = create("./sprites/mario2-big.png");

var enemies = create("./sprites/enemies.png");

var items = create("./sprites/items.png");

var blocks = create("./sprites/blocks.png");

var panel = create("./sprites/panel.png");

var ground = create("./sprites/ground.png");

var chunks = create("./sprites/chunks.png");

var score = create("./sprites/score.png");

var bgd1 = create("./sprites/bgd-1.png");

var Png = {
  create: create,
  marioSmall: marioSmall,
  mario2Small: mario2Small,
  marioBig: marioBig,
  mario2Big: mario2Big,
  enemies: enemies,
  items: items,
  blocks: blocks,
  panel: panel,
  ground: ground,
  chunks: chunks,
  score: score,
  bgd1: bgd1
};

function smallPlayerParams(typ, dir, playerNum) {
  var png = playerNum ? mario2Small : marioSmall;
  if (dir) {
    switch (typ) {
      case /* Standing */0 :
          return spriteParams([
                      1,
                      1
                    ], [
                      11,
                      15
                    ], undefined, undefined, undefined, [
                      0,
                      32
                    ], png);
      case /* Jumping */1 :
          return spriteParams([
                      2,
                      1
                    ], [
                      13,
                      15
                    ], undefined, 10, 2, [
                      16,
                      48
                    ], png);
      case /* Running */2 :
          return spriteParams([
                      2,
                      1
                    ], [
                      12,
                      15
                    ], undefined, 5, 3, [
                      16,
                      32
                    ], png);
      case /* Crouching */3 :
          return spriteParams([
                      1,
                      5
                    ], [
                      14,
                      10
                    ], undefined, undefined, undefined, [
                      0,
                      64
                    ], png);
      
    }
  } else {
    switch (typ) {
      case /* Standing */0 :
          return spriteParams([
                      3,
                      1
                    ], [
                      11,
                      15
                    ], undefined, undefined, undefined, [
                      0,
                      0
                    ], png);
      case /* Jumping */1 :
          return spriteParams([
                      2,
                      1
                    ], [
                      13,
                      15
                    ], undefined, 10, 2, [
                      16,
                      16
                    ], png);
      case /* Running */2 :
          return spriteParams([
                      2,
                      1
                    ], [
                      12,
                      15
                    ], undefined, 5, 3, [
                      16,
                      0
                    ], png);
      case /* Crouching */3 :
          return spriteParams([
                      1,
                      5
                    ], [
                      14,
                      10
                    ], undefined, undefined, undefined, [
                      0,
                      64
                    ], png);
      
    }
  }
}

function bigPlayerParams(typ, dir, playerNum) {
  var png = playerNum ? mario2Big : marioBig;
  if (dir) {
    switch (typ) {
      case /* Standing */0 :
          return spriteParams([
                      1,
                      1
                    ], [
                      13,
                      25
                    ], [
                      16,
                      26
                    ], undefined, undefined, [
                      16,
                      69
                    ], png);
      case /* Jumping */1 :
          return spriteParams([
                      2,
                      1
                    ], [
                      12,
                      25
                    ], [
                      16,
                      26
                    ], undefined, undefined, [
                      48,
                      70
                    ], png);
      case /* Running */2 :
          return spriteParams([
                      2,
                      1
                    ], [
                      13,
                      25
                    ], [
                      16,
                      27
                    ], 10, 4, [
                      0,
                      101
                    ], png);
      case /* Crouching */3 :
          return spriteParams([
                      2,
                      10
                    ], [
                      13,
                      17
                    ], [
                      16,
                      27
                    ], undefined, undefined, [
                      32,
                      69
                    ], png);
      
    }
  } else {
    switch (typ) {
      case /* Standing */0 :
          return spriteParams([
                      2,
                      1
                    ], [
                      13,
                      25
                    ], [
                      16,
                      27
                    ], undefined, undefined, [
                      16,
                      5
                    ], png);
      case /* Jumping */1 :
          return spriteParams([
                      2,
                      1
                    ], [
                      12,
                      25
                    ], [
                      16,
                      26
                    ], undefined, undefined, [
                      48,
                      6
                    ], png);
      case /* Running */2 :
          return spriteParams([
                      2,
                      1
                    ], [
                      13,
                      25
                    ], [
                      16,
                      27
                    ], 10, 4, [
                      0,
                      37
                    ], png);
      case /* Crouching */3 :
          return spriteParams([
                      2,
                      10
                    ], [
                      13,
                      17
                    ], [
                      16,
                      27
                    ], undefined, undefined, [
                      32,
                      5
                    ], png);
      
    }
  }
}

function enemyParams(typ, dir) {
  switch (typ) {
    case /* Goomba */0 :
        return spriteParams([
                    1,
                    1
                  ], [
                    14,
                    14
                  ], undefined, 10, 2, [
                    0,
                    128
                  ], enemies);
    case /* GKoopa */1 :
        if (dir) {
          return spriteParams([
                      1,
                      10
                    ], [
                      11,
                      16
                    ], [
                      16,
                      27
                    ], 10, 2, [
                      32,
                      69
                    ], enemies);
        } else {
          return spriteParams([
                      4,
                      10
                    ], [
                      11,
                      16
                    ], [
                      16,
                      27
                    ], 10, 2, [
                      0,
                      69
                    ], enemies);
        }
    case /* RKoopa */2 :
        if (dir) {
          return spriteParams([
                      1,
                      10
                    ], [
                      11,
                      16
                    ], [
                      16,
                      27
                    ], 10, 2, [
                      32,
                      5
                    ], enemies);
        } else {
          return spriteParams([
                      4,
                      10
                    ], [
                      11,
                      16
                    ], [
                      16,
                      27
                    ], 10, 2, [
                      0,
                      5
                    ], enemies);
        }
    case /* GKoopaShell */3 :
        return spriteParams([
                    2,
                    2
                  ], [
                    12,
                    13
                  ], undefined, 10, 4, [
                    0,
                    96
                  ], enemies);
    case /* RKoopaShell */4 :
        return spriteParams([
                    2,
                    2
                  ], [
                    12,
                    13
                  ], undefined, 10, 4, [
                    0,
                    32
                  ], enemies);
    
  }
}

function makeParams(x) {
  if (x) {
    return spriteParams([
                3,
                0
              ], [
                12,
                16
              ], undefined, 15, 3, [
                0,
                80
              ], items);
  } else {
    return spriteParams([
                2,
                0
              ], [
                12,
                16
              ], undefined, undefined, undefined, [
                0,
                0
              ], items);
  }
}

var brickParams = spriteParams(undefined, undefined, undefined, 10, 5, [
      0,
      0
    ], blocks);

var qBlockParams = spriteParams(undefined, undefined, undefined, 15, 4, [
      0,
      16
    ], blocks);

var qBlockUsedParams = spriteParams(undefined, undefined, undefined, undefined, undefined, [
      0,
      32
    ], blocks);

var unBBlockParams = spriteParams(undefined, undefined, undefined, undefined, undefined, [
      0,
      48
    ], blocks);

var cloudParams = spriteParams(undefined, undefined, undefined, undefined, undefined, [
      0,
      64
    ], blocks);

var panelParams = spriteParams(undefined, undefined, [
      26,
      26
    ], 15, 3, [
      0,
      0
    ], panel);

var groundParams = spriteParams(undefined, undefined, undefined, undefined, undefined, [
      0,
      32
    ], ground);

function blockParams(x) {
  if (typeof x !== "number") {
    return qBlockParams;
  }
  switch (x) {
    case /* QBlockUsed */0 :
        return qBlockUsedParams;
    case /* Brick */1 :
        return brickParams;
    case /* UnBBlock */2 :
        return unBBlockParams;
    case /* Cloud */3 :
        return cloudParams;
    case /* Panel */4 :
        return panelParams;
    case /* Ground */5 :
        return groundParams;
    
  }
}

function particleParams(x) {
  switch (x) {
    case /* GoombaSquish */0 :
        return spriteParams(undefined, undefined, undefined, undefined, undefined, [
                    0,
                    144
                  ], enemies);
    case /* BrickChunkL */1 :
        return spriteParams(undefined, undefined, [
                    8,
                    8
                  ], undefined, undefined, [
                    0,
                    0
                  ], chunks);
    case /* BrickChunkR */2 :
        return spriteParams(undefined, undefined, [
                    8,
                    8
                  ], undefined, undefined, [
                    8,
                    0
                  ], chunks);
    case /* Score100 */3 :
        return spriteParams(undefined, undefined, [
                    12,
                    8
                  ], undefined, undefined, [
                    0,
                    0
                  ], score);
    case /* Score200 */4 :
        return spriteParams(undefined, undefined, [
                    12,
                    9
                  ], undefined, undefined, [
                    0,
                    9
                  ], score);
    case /* Score400 */5 :
        return spriteParams(undefined, undefined, [
                    12,
                    9
                  ], undefined, undefined, [
                    0,
                    18
                  ], score);
    case /* Score800 */6 :
        return spriteParams(undefined, undefined, [
                    12,
                    9
                  ], undefined, undefined, [
                    0,
                    27
                  ], score);
    case /* Score1000 */7 :
        return spriteParams(undefined, undefined, [
                    14,
                    9
                  ], undefined, undefined, [
                    13,
                    0
                  ], score);
    case /* Score2000 */8 :
        return spriteParams(undefined, undefined, [
                    14,
                    9
                  ], undefined, undefined, [
                    13,
                    9
                  ], score);
    case /* Score4000 */9 :
        return spriteParams(undefined, undefined, [
                    14,
                    9
                  ], undefined, undefined, [
                    13,
                    18
                  ], score);
    case /* Score8000 */10 :
        return spriteParams(undefined, undefined, [
                    14,
                    9
                  ], undefined, undefined, [
                    13,
                    27
                  ], score);
    
  }
}

function playerParams(plSize, typ, dir, playerNum) {
  if (plSize) {
    return smallPlayerParams(typ, dir, playerNum);
  } else {
    return bigPlayerParams(typ, dir, playerNum);
  }
}

function makeFromParams(params) {
  return {
          params: params,
          frame: 0,
          ticks: 0
        };
}

function makeBgd(param) {
  return {
          params: spriteParams(undefined, undefined, [
                512,
                256
              ], undefined, undefined, [
                0,
                0
              ], bgd1),
          frame: 0,
          ticks: 0
        };
}

function makeParticle(ptyp) {
  return {
          params: particleParams(ptyp),
          frame: 0,
          ticks: 0
        };
}

function transformEnemy(enemy_typ, spr, dir) {
  var params = enemyParams(enemy_typ, dir);
  spr.params = params;
  
}

function updateAnimation(spr) {
  var curr_ticks = spr.ticks;
  if (curr_ticks >= spr.params.maxTicks) {
    spr.ticks = 0;
    spr.frame = Caml_int32.mod_(spr.frame + 1 | 0, spr.params.maxFrames);
  } else {
    spr.ticks = curr_ticks + 1 | 0;
  }
  
}

export {
  spriteParams ,
  Png ,
  smallPlayerParams ,
  bigPlayerParams ,
  enemyParams ,
  makeParams ,
  brickParams ,
  qBlockParams ,
  qBlockUsedParams ,
  unBBlockParams ,
  cloudParams ,
  panelParams ,
  groundParams ,
  blockParams ,
  particleParams ,
  playerParams ,
  makeFromParams ,
  makeBgd ,
  makeParticle ,
  transformEnemy ,
  updateAnimation ,
  
}
/* marioSmall Not a pure module */
