// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sprite from "./Sprite.js";
import * as Viewport from "./Viewport.js";
import * as Generator from "./Generator.js";

function $$new(date, level, score) {
  var viewport = Viewport.make(level);
  var incompleteState = {
    bgd: Sprite.makeBgd(undefined),
    coins: 0,
    date: date,
    idCounter: 0,
    level: level,
    multiplier: 1,
    objects: [],
    particles: [],
    player1: 0,
    player2: 0,
    score: score,
    viewport: viewport
  };
  var player1 = Generator.newPlayer(/* One */0, incompleteState);
  var player2 = Generator.newPlayer(/* Two */1, incompleteState);
  Viewport.update(viewport, player1.px, player1.py);
  Generator.generate(incompleteState);
  return {
          bgd: incompleteState.bgd,
          coins: incompleteState.coins,
          date: incompleteState.date,
          idCounter: incompleteState.idCounter,
          level: incompleteState.level,
          multiplier: incompleteState.multiplier,
          objects: incompleteState.objects,
          particles: incompleteState.particles,
          player1: player1,
          player2: player2,
          score: incompleteState.score,
          viewport: incompleteState.viewport
        };
}

function updateScore(state, i) {
  state.score = state.score + i | 0;
  
}

export {
  $$new ,
  updateScore ,
  
}
/* Sprite Not a pure module */
